target = 'StartMenu'

files = Split("""
	StartMenu.c
""")

resources = Split("""
	StartMenu.rc
""")

libs = Split("""
	kernel32
	user32
	gdi32
	shell32
	ole32
""")

docs = Split("""
	Readme.txt
""")

Import('BuildPlugin env')

if env['UNICODE']:
	examples = Split("""
		Unicode/Example.nsi
	""")
else:
	examples = Split("""
		ANSI/Example.nsi
	""")

BuildPlugin(target, files, libs, examples, docs, res = resources)
