includes = Split("""
	Colors.nsh
	FileFunc.nsh
	LangFile.nsh
	Library.nsh
	LogicLib.nsh
	Memento.nsh
	MUI.nsh
	MUI2.nsh
	Sections.nsh
	StrFunc.nsh
	TextFunc.nsh
	Util.nsh
	UpgradeDLL.nsh
	VB6RunTime.nsh
	WinCore.nsh
	WinMessages.nsh
	WinVer.nsh
	WordFunc.nsh
	x64.nsh
""")

includesWin = [
	'Win/WinDef.nsh',
	'Win/WinError.nsh',
	'Win/WinNT.nsh',
	'Win/WinUser.nsh'
]

Import('env')
temp = []

if env['UNICODE']:
	for x in includes:
		temp.append('Unicode/' + x)
	includes = temp
else:
	for x in includes:
		temp.append('ANSI/' + x)
	includes = temp

env.DistributeInclude(includes)
env.DistributeInclude(includesWin, path='Win')
env.DistributeDocs('StrFunc.txt', path='StrFunc')
