target = 'InstallOptions'

files = Split("""
	InstallerOptions.cpp
""")

resources = Split("""
	ioptdll.rc
""")

libs = Split("""
	kernel32
	user32
	gdi32
	shell32
	comdlg32
	ole32
""")

examples = Split("""
	test.nsi
	test.ini
	testimgs.nsi
	testimgs.ini
	testlink.nsi
	testlink.ini
	testnotify.nsi
	testnotify.ini
""")

docs = Split("""
	Changelog.txt
	Readme.html
""")

includes = Split("""
	InstallOptions.nsh
""")

Import('BuildPlugin env')

if env['UNICODE']:
	temp = []
	for x in examples:
		temp.append('Unicode/' + x)
	examples = temp

	temp = []
	for x in includes:
		temp.append('Unicode/' + x)
	includes = temp
else:
	temp = []
	for x in examples:
		temp.append('ANSI/' + x)
	examples = temp

	temp = []
	for x in includes:
		temp.append('ANSI/' + x)
	includes = temp

BuildPlugin(target, files, libs, examples, docs, res = resources)
env.DistributeInclude(includes)
