target = 'BgImage'

files = Split("""
	BgImage.cpp
""")

libs = Split("""
	kernel32
	user32
	gdi32
	winmm
""")

docs = Split("""
	BgImage.txt
""")

Import('BuildPlugin env')

if env['UNICODE']:
	examples = Split("""
		Unicode/Example.nsi
	""")
else:
	examples = Split("""
		ANSI/Example.nsi
	""")

BuildPlugin(target, files, libs, examples, docs)
