target = 'nsDialogs'

files = Split("""
   browse.c
   input.c
   nsDialogs.c
   nsDialogs.def
   rtl.c
""")

resources = Split("""
   dialog.rc
""")

libs = Split("""
   kernel32
   user32
   gdi32
   shell32
   comdlg32
   ole32
""")

docs = Split("""
   Readme.html
""")

Import('BuildPlugin env')

if env['UNICODE']:
   examples = Split("""
      Unicode/example.nsi
      Unicode/InstallOptions.nsi
      Unicode/welcome.nsi
      Unicode/timer.nsi
   """)

   includes = Split("""
      Unicode/nsDialogs.nsh
   """)
else:
   examples = Split("""
      ANSI/example.nsi
      ANSI/InstallOptions.nsi
      ANSI/welcome.nsi
      ANSI/timer.nsi   
   """)

   includes = Split("""
      ANSI/nsDialogs.nsh
   """)

BuildPlugin(target, files, libs, examples, docs, res = resources)
env.DistributeInclude(includes)
