target = 'UserInfo'

files = Split("""
	UserInfo.c
""")

libs = Split("""
	kernel32
	advapi32
	user32
""")

Import('BuildPlugin env')

if env['UNICODE']:
	examples = Split("""
		Unicode/UserInfo.nsi
	""")
else:
	examples = Split("""
		ANSI/UserInfo.nsi
	""")

BuildPlugin(target, files, libs, examples)
